import type { ScenarioInput } from "./calculator";

export const DEFAULT_SCENARIOS: ScenarioInput[] = [
  {
    id: "lease-model-y",
    kind: "lease",
    car: {
      name: "Tesla Model Y Leasing",
      condition: "new",
      startMonth: 1,
      blpGross: 52990,
      purchasePriceGross: 52990,
      vatRate: 0.19,
      vatMode: "regular",
      firstRegistrationYear: 2026,
      afaYears: 6,
      privateUseMethod: "auto-bev",
      privateUseRate: 0.0025,
      commuteDistanceKm: 0,
      commuteDistanceKmEnabled: false,
      commuteMonthsPerYear: 12,
      commuteMonthsPerYearEnabled: false,
      commuteDaysPerMonth: 0,
      commuteDaysPerMonthEnabled: false,
      annualInsuranceGross: 1200,
      annualInsuranceGrossEnabled: true,
      annualChargingGross: 900,
      annualChargingGrossEnabled: true,
      annualMaintenanceGross: 450,
      annualMaintenanceGrossEnabled: true,
      annualTiresGross: 250,
      annualTiresGrossEnabled: true,
      salePriceMode: "gross",
      salePriceNet: 0,
      salePriceNetEnabled: false,
      saleAfterMonths: 0,
      saleAfterMonthsEnabled: false,
    },
    lease: {
      termMonths: 36,
      monthlyRateGross: 690,
      specialPaymentGross: 3000,
      feesGross: 1190,
    },
  },
  {
    id: "credit-new-ix1",
    kind: "credit-new",
    car: {
      name: "BMW iX1 Ballonkredit neu",
      condition: "new",
      startMonth: 1,
      blpGross: 56900,
      purchasePriceGross: 53500,
      vatRate: 0.19,
      vatMode: "regular",
      firstRegistrationYear: 2026,
      afaYears: 6,
      privateUseMethod: "auto-bev",
      privateUseRate: 0.0025,
      commuteDistanceKm: 0,
      commuteDistanceKmEnabled: false,
      commuteMonthsPerYear: 12,
      commuteMonthsPerYearEnabled: false,
      commuteDaysPerMonth: 0,
      commuteDaysPerMonthEnabled: false,
      annualInsuranceGross: 1200,
      annualInsuranceGrossEnabled: true,
      annualChargingGross: 900,
      annualChargingGrossEnabled: true,
      annualMaintenanceGross: 450,
      annualMaintenanceGrossEnabled: true,
      annualTiresGross: 250,
      annualTiresGrossEnabled: true,
      salePriceMode: "gross",
      salePriceNet: 0,
      salePriceNetEnabled: false,
      saleAfterMonths: 0,
      saleAfterMonthsEnabled: false,
    },
    credit: {
      termMonths: 48,
      downPaymentGross: 8000,
      annualInterestRate: 0.049,
      balloonGross: 23500,
      acquisitionCostsGross: 990,
      feesGross: 790,
    },
  },
  {
    id: "credit-used-id4",
    kind: "credit-used",
    car: {
      name: "VW ID.4 Ballonkredit gebraucht",
      condition: "used",
      startMonth: 1,
      blpGross: 52900,
      purchasePriceGross: 34900,
      vatRate: 0.19,
      vatMode: "none",
      firstRegistrationYear: 2023,
      afaYears: 3,
      privateUseMethod: "auto-bev",
      privateUseRate: 0.0025,
      commuteDistanceKm: 0,
      commuteDistanceKmEnabled: false,
      commuteMonthsPerYear: 12,
      commuteMonthsPerYearEnabled: false,
      commuteDaysPerMonth: 0,
      commuteDaysPerMonthEnabled: false,
      annualInsuranceGross: 1000,
      annualInsuranceGrossEnabled: true,
      annualChargingGross: 850,
      annualChargingGrossEnabled: true,
      annualMaintenanceGross: 650,
      annualMaintenanceGrossEnabled: true,
      annualTiresGross: 300,
      annualTiresGrossEnabled: true,
      salePriceMode: "gross",
      salePriceNet: 0,
      salePriceNetEnabled: false,
      saleAfterMonths: 0,
      saleAfterMonthsEnabled: false,
    },
    credit: {
      termMonths: 36,
      downPaymentGross: 6000,
      annualInterestRate: 0.065,
      balloonGross: 14500,
      acquisitionCostsGross: 590,
      feesGross: 490,
    },
  },
];
